# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pushNotif' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pushNotif
  pod 'Firebase/Core'

  target 'pushNotif-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pushNotifTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'pushNotif-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
